#!/usr/bin/env python3
"""Generate crystal_ball/item_names.h: a host-side `item_from_name` lookup.

The device `Item` enum (../lib/items.cl, upstream) is purely sequential, so the
host can reproduce each member's integer value by counting declaration order. We
assert no explicit `= value` exists, since that would break the index alignment.

Usage: python3 crystal_ball/gen_item_names.py
Out:   crystal_ball/item_names.h
"""
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent  # Immolate/crystal_ball
SRC = HERE.parent / "lib" / "items.cl"  # upstream enum stays in Immolate/lib
OUT = HERE / "item_names.h"


def extract_enum_members(text: str) -> list[str]:
    """Return Item enum member identifiers in declaration order.

    raises: SystemExit if the enum isn't found or contains `= value`.
    """
    m = re.search(r"typedef\s+enum\s+Item\s*\{(.*?)\}\s*item\s*;", text, re.S)
    if not m:
        sys.exit("error: `typedef enum Item { ... } item;` not found")
    body = m.group(1)
    # Strip // and /* */ comments.
    body = re.sub(r"//[^\n]*", "", body)
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    if "=" in body:
        sys.exit("error: Item enum has explicit `=`; index alignment broken")
    members = [tok.strip() for tok in body.split(",")]
    return [t for t in members if re.fullmatch(r"[A-Za-z_]\w*", t)]


def render(members: list[str]) -> str:
    lines = [
        "// GENERATED by gen_item_names.py - do not edit.",
        "// Maps an Item enum identifier (e.g. \"Blueprint\") to its integer value.",
        "#ifndef ITEM_NAMES_H",
        "#define ITEM_NAMES_H",
        "#include <string.h>",
        "",
        "// returns: enum value, or -1 if name is unknown.",
        "static int item_from_name(const char* name) {",
    ]
    for idx, member in enumerate(members):
        lines.append(f'    if (strcmp(name, "{member}") == 0) return {idx};')
    lines += [
        "    return -1;",
        "}",
        "",
        "#endif",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    members = extract_enum_members(SRC.read_text())
    OUT.write_text(render(members))
    print(f"wrote {OUT} ({len(members)} items)")


if __name__ == "__main__":
    main()
